# Homework for Week 6

The goal for this homework is to see the relevant journalistic uses for what we learned in class.

1. Ingest different types of spreadsheets into Pandas,
2. Gather general info about our dataframes
3. Target specific values

## Pandas - Importing data

Please download the following data and move it to an appropriate folder on your computer:

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/ems20_1st_6months_excerpt.csv">EMS excerpt</a>,

- <a href="https://github.com/sandeepmj/datasets/blob/main/importing-excerpts/multi-data.xlsx">Customs, Border Patrol</a>

**Give yourself time to download it. Some of the files are large!**

In [2]:
## import the pandas library in this cell
import pandas as pd

### Ingest the following dataset into this note:

- ```ems20_1st_6months_excerpt.csv``` into a dataframe named ```ems2020_excerpt_df```

In [6]:
## import data and store in dataframe
ems2020_excerpt_df = pd.read_csv("data-raw/ems20_1st_6months_excerpt.csv")

In [8]:
## call the first 10 rows
ems2020_excerpt_df.head(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv
7,201471743,2020-05-26 12:45:46,INJURY,5,INJURY,5,05/26/2020 12:46:04 PM,Y,18,05/26/2020 12:46:15 PM,...,41.0,17.0,202.0,8.0,15.0,N,N,N,N,chunk171.csv
8,201180116,2020-04-27 00:57:48,EDP,7,EDPC,7,04/27/2020 12:58:07 AM,Y,19,04/27/2020 12:58:15 AM,...,50.0,11.0,208.0,10.0,16.0,N,N,N,N,chunk170.csv
9,200572739,2020-02-26 15:15:25,CARDBR,2,CARDBR,2,02/26/2020 03:16:35 PM,Y,70,02/26/2020 03:16:49 PM,...,106.0,28.0,410.0,27.0,5.0,N,N,N,N,chunk167.csv

In [10]:
## call the last 5 rows
ems2020_excerpt_df.tail()

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [12]:
## call a 20 random rows
ems2020_excerpt_df.sample(20)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
1647,200761156,2020-03-16 08:43:23,UNKNOW,4,UNKNOW,4,03/16/2020 08:44:26 AM,Y,63,03/16/2020 08:45:00 AM,...,46.0,16.0,205.0,9.0,13.0,N,N,N,N,chunk168.csv
7140,200393977,2020-02-08 22:12:09,CARD,3,CARD,3,02/08/2020 10:12:35 PM,Y,26,02/08/2020 10:12:54 PM,...,67.0,42.0,317.0,18.0,9.0,N,N,N,N,chunk166.csv
2339,201021669,2020-04-11 10:37:45,EDP,7,EDP,7,04/11/2020 10:39:09 AM,Y,84,04/11/2020 10:40:04 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk169.csv
9141,201531578,2020-06-01 11:58:03,INJURY,5,INJURY,5,06/01/2020 11:58:22 AM,Y,19,06/01/2020 11:59:07 AM,...,34.0,10.0,112.0,6.0,13.0,N,N,N,N,chunk171.csv
6929,200855548,2020-03-25 20:38:35,DIFFBR,2,DIFFBR,2,03/25/2020 08:39:06 PM,Y,31,03/25/2020 08:39:29 PM,...,63.0,46.0,318.0,22.0,8.0,N,N,N,N,chunk168.csv
4302,201350744,2020-05-14 06:49:30,CARDBR,2,CARDBR,2,05/14/2020 06:50:15 AM,Y,45,05/14/2020 06:50:26 AM,...,110.0,21.0,404.0,24.0,14.0,N,N,N,N,chunk170.csv
7660,200260249,2020-01-26 01:21:19,INJURY,5,INJURY,5,01/26/2020 01:22:09 AM,Y,50,01/26/2020 01:22:24 AM,...,43.0,18.0,209.0,12.0,15.0,N,N,N,N,chunk166.csv
10959,201420523,2020-05-21 04:34:15,SICK,6,SICK,6,05/21/2020 04:34:22 AM,Y,7,05/21/2020 04:34:37 AM,...,110.0,25.0,404.0,24.0,6.0,N,N,N,N,chunk171.csv
6046,200831513,2020-03-23 09:32:08,ASTHMB,2,ASTHMB,2,03/23/2020 09:32:25 AM,Y,17,03/23/2020 09:32:35 AM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv
12891,200294434,2020-01-29 22:29:02,SICK,6,SICK,6,01/29/2020 10:29:16 PM,Y,14,01/29/2020 10:29:30 PM,...,73.0,42.0,316.0,23.0,9.0,N,N,N,N,chunk166.csv
1074,201730890,2020-06-21 06:06:04,INJURY,5,INJMAJ,3,06/21/2020 06:06:11 AM,Y,7,06/21/2020 06:06:20 AM,...,10.0,3.0,104.0,2.0,10.0,N,N,N,N,chunk172.csv
11664,200841333,2020-03-24 08:29:37,DIFFBR,2,DIFFBR,2,03/24/2020 08:29:51 AM,Y,14,03/24/2020 08:30:25 AM,...,121.0,49.0,501.0,31.0,11.0,N,N,N,N,chunk168.csv
6600,200831901,2020-03-23 10:44:09,ABDPN,5,ABDPN,5,03/23/2020 12:16:17 PM,Y,5528,03/23/2020 12:16:30 PM,...,107.0,23.0,408.0,26.0,6.0,N,N,N,N,chunk168.csv
2988,201721431,2020-06-20 11:18:23,DIFFBR,2,DIFFBR,2,06/20/2020 11:19:39 AM,Y,76,06/20/2020 11:19:56 AM,...,33.0,10.0,112.0,NaN,13.0,N,N,N,N,chunk172.csv
8348,201433311,2020-05-22 20:44:38,UNC,2,UNC,2,05/22/2020 08:44:44 PM,Y,6,05/22/2020 08:45:04 PM,...,67.0,40.0,317.0,17.0,9.0,N,N,N,N,chunk171.csv
10389,201273325,2020-05-06 21:18:21,CARDBR,2,CARDBR,2,05/06/2020 09:18:35 PM,Y,14,05/06/2020 09:18:50 PM,...,109.0,19.0,407.0,25.0,6.0,N,N,N,N,chunk170.csv
9868,201510520,2020-05-30 03:41:33,CDBRFC,2,CDBRFC,2,05/30/2020 03:41:48 AM,Y,15,05/30/2020 03:42:12 AM,...,83.0,37.0,304.0,32.0,7.0,N,N,N,N,chunk171.csv
8543,200661062,2020-03-06 08:25:16,CVA,4,SICK,6,03/06/2020 08:25:23 AM,Y,7,03/06/2020 08:26:40 AM,...,32.0,9.0,110.0,5.0,13.0,N,N,N,N,chunk167.csv
11071,200041218,2020-01-04 09:14:55,UNKNOW,4,UNKNOW,4,01/04/2020 09:15:20 AM,Y,25,01/04/2020 09:15:31 AM,...,71.0,41.0,309.0,17.0,9.0,N,N,N,N,chunk165.csv
10970,201540419,2020-06-02 02:34:46,EDP,7,EDP,7,06/02/2020 02:35:22 AM,Y,36,06/02/2020 02:35:31 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk171.csv

In [14]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
ems2020_excerpt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13117 entries, 0 to 13116
Data columns (total 32 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   CAD_INCIDENT_ID                 13117 non-null  int64
 1   INCIDENT_DATETIME               13117 non-null  object
 2   INITIAL_CALL_TYPE               13117 non-null  object
 3   INITIAL_SEVERITY_LEVEL_CODE     13117 non-null  int64
 4   FINAL_CALL_TYPE                 13117 non-null  object
 5   FINAL_SEVERITY_LEVEL_CODE       13117 non-null  int64
 6   FIRST_ASSIGNMENT_DATETIME       13010 non-null  object
 7   VALID_DISPATCH_RSPNS_TIME_INDC  13117 non-null  object
 8   DISPATCH_RESPONSE_SECONDS_QY    13117 non-null  int64
 9   FIRST_ACTIVATION_DATETIME       12988 non-null  object
 10  FIRST_ON_SCENE_DATETIME         12533 non-null  object
 11  VALID_INCIDENT_RSPNS_TIME_INDC  13117 non-null  object
 12  INCIDENT_RESPONSE_SECONDS_QY    12533 non-null  float64
 13  INCIDENT_TRAVEL_TM_SECONDS_QY   12533 non-null  float64
 14  FIRST_TO_HOSP_DATETIME          7870 non-null   object
 15  FIRST_HOSP_ARRIVAL_DATETIME     7791 non-null   object
 16  INCIDENT_CLOSE_DATETIME         13110 non-null  object
 17  HELD_INDICATOR                  13117 non-null  object
 18  INCIDENT_DISPOSITION_CODE       12985 non-null  float64
 19  BOROUGH                         13117 non-null  object
 20  INCIDENT_DISPATCH_AREA          13117 non-null  object
 21  ZIPCODE                         12987 non-null  float64
 22  POLICEPRECINCT                  12988 non-null  float64
 23  CITYCOUNCILDISTRICT             12988 non-null  float64
 24  COMMUNITYDISTRICT               12988 non-null  float64
 25  COMMUNITYSCHOOLDISTRICT         12978 non-null  float64
 26  CONGRESSIONALDISTRICT           12988 non-null  float64
 27  REOPEN_INDICATOR                13117 non-null  object
 28  SPECIAL_EVENT_INDICATOR         13117 non-null  object
 29  STANDBY_INDICATOR               13117 non-null  object
 30  TRANSFER_INDICATOR              13117 non-null  object
 31  source                          13117 non-null  object
dtypes: float64(9), int64(4), object(19)
memory usage: 3.2+ MB

In [16]:
## call the top 7 rows
ems2020_excerpt_df.head(7)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
0,201101264,2020-04-19 10:25:47,INJMIN,7,INJMIN,7,04/19/2020 10:26:24 AM,Y,37,04/19/2020 10:26:24 AM,...,40.0,8.0,201.0,7.0,15.0,N,N,N,N,chunk170.csv
1,200423766,2020-02-11 19:25:47,CARD,3,SICK,6,02/11/2020 07:25:56 PM,Y,9,02/11/2020 07:26:09 PM,...,52.0,14.0,207.0,10.0,15.0,N,N,N,N,chunk166.csv
2,200434110,2020-02-12 21:36:52,UNC,2,UNC,2,02/12/2020 09:37:24 PM,Y,32,02/12/2020 09:38:27 PM,...,106.0,32.0,410.0,27.0,8.0,N,N,N,N,chunk166.csv
3,201610121,2020-06-09 00:52:30,DRUG,4,DRUG,4,06/09/2020 12:52:44 AM,Y,14,06/09/2020 12:52:59 AM,...,19.0,4.0,108.0,2.0,12.0,N,N,N,N,chunk171.csv
4,200034112,2020-01-03 20:44:05,DRUG,4,DRUG,4,01/03/2020 08:44:11 PM,Y,6,01/03/2020 08:44:17 PM,...,66.0,39.0,312.0,15.0,7.0,N,N,N,N,chunk165.csv
5,200530247,2020-02-22 01:26:18,DRUG,4,DRUG,4,02/22/2020 01:27:21 AM,Y,63,02/22/2020 01:27:41 AM,...,25.0,8.0,111.0,4.0,12.0,N,N,N,N,chunk167.csv
6,200543279,2020-02-23 19:08:27,UNC,2,UNC,2,02/23/2020 07:08:44 PM,Y,17,02/23/2020 07:09:16 PM,...,44.0,8.0,204.0,9.0,15.0,N,N,N,N,chunk167.csv

In [18]:
## call a sample of 10
ems2020_excerpt_df.sample(10)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
3635,201780852,2020-06-26 07:24:20,MVAINJ,4,MVAINJ,4,06/26/2020 07:25:04 AM,Y,44,06/26/2020 07:25:16 AM,...,NaN,NaN,NaN,NaN,NaN,N,N,N,N,chunk172.csv
8632,200190374,2020-01-19 02:18:43,EDP,7,EDPC,7,01/19/2020 02:19:06 AM,Y,23,01/19/2020 02:19:24 AM,...,25.0,8.0,111.0,4.0,13.0,N,N,N,N,chunk165.csv
6505,201810731,2020-06-29 06:21:17,UNKNOW,4,EDP,7,06/29/2020 06:21:37 AM,Y,20,06/29/2020 06:22:12 AM,...,47.0,12.0,212.0,11.0,16.0,N,N,N,N,chunk172.csv
11640,201131034,2020-04-22 09:39:00,SICMIN,7,UNKNOW,4,04/22/2020 09:41:24 AM,Y,144,04/22/2020 09:41:32 AM,...,46.0,14.0,205.0,9.0,15.0,Y,N,N,N,chunk170.csv
11111,201662143,2020-06-14 15:33:47,ALTMEN,3,ALTMEN,3,06/14/2020 03:34:11 PM,Y,24,06/14/2020 03:34:17 PM,...,88.0,35.0,302.0,13.0,8.0,N,N,N,N,chunk171.csv
9629,201463055,2020-05-25 20:16:09,CVAC,2,ALTMEN,3,05/25/2020 08:16:24 PM,Y,15,05/25/2020 08:16:33 PM,...,123.0,51.0,503.0,31.0,11.0,N,N,N,N,chunk171.csv
5252,200154275,2020-01-15 20:45:13,SICK,6,SICK,6,01/15/2020 08:45:21 PM,Y,8,01/15/2020 08:45:37 PM,...,13.0,4.0,106.0,2.0,12.0,N,N,N,N,chunk165.csv
9790,200494583,2020-02-18 23:58:00,SICK,6,SICK,6,02/18/2020 11:58:14 PM,Y,14,02/18/2020 11:58:33 PM,...,84.0,33.0,302.0,15.0,7.0,N,N,N,N,chunk167.csv
12223,201230600,2020-05-02 04:43:45,CARDBR,2,CARDBR,2,05/02/2020 04:43:56 AM,Y,11,05/02/2020 04:44:13 AM,...,24.0,6.0,107.0,3.0,13.0,N,N,N,N,chunk170.csv
5925,200203449,2020-01-20 19:44:45,ASTHMB,2,ASTHMB,2,01/20/2020 07:47:30 PM,Y,165,01/20/2020 07:47:52 PM,...,50.0,14.0,208.0,10.0,13.0,N,N,N,N,chunk165.csv

In [20]:
## call the bottom 6
ems2020_excerpt_df.tail(6)

,CAD_INCIDENT_ID,INCIDENT_DATETIME,INITIAL_CALL_TYPE,INITIAL_SEVERITY_LEVEL_CODE,FINAL_CALL_TYPE,FINAL_SEVERITY_LEVEL_CODE,FIRST_ASSIGNMENT_DATETIME,VALID_DISPATCH_RSPNS_TIME_INDC,DISPATCH_RESPONSE_SECONDS_QY,FIRST_ACTIVATION_DATETIME,...,POLICEPRECINCT,CITYCOUNCILDISTRICT,COMMUNITYDISTRICT,COMMUNITYSCHOOLDISTRICT,CONGRESSIONALDISTRICT,REOPEN_INDICATOR,SPECIAL_EVENT_INDICATOR,STANDBY_INDICATOR,TRANSFER_INDICATOR,source
13111,200870168,2020-03-27 00:42:59,INJURY,5,INJURY,5,03/27/2020 12:43:13 AM,Y,14,03/27/2020 12:43:28 AM,...,109.0,19.0,407.0,25.0,3.0,N,N,N,N,chunk168.csv
13112,200393407,2020-02-08 19:49:33,DIFFBR,2,DIFFBR,2,02/08/2020 07:52:34 PM,Y,181,02/08/2020 07:53:00 PM,...,72.0,38.0,307.0,15.0,7.0,N,N,N,N,chunk166.csv
13113,200034618,2020-01-03 22:51:33,INJURY,5,INJURY,5,01/03/2020 10:51:39 PM,Y,6,01/03/2020 10:52:21 PM,...,75.0,42.0,305.0,19.0,8.0,N,N,N,N,chunk165.csv
13114,200424355,2020-02-11 21:51:09,SICK,6,SICK,6,02/11/2020 09:52:09 PM,Y,60,02/11/2020 09:52:18 PM,...,48.0,15.0,206.0,10.0,15.0,N,N,N,N,chunk166.csv
13115,201742708,2020-06-22 15:57:44,MVAINJ,4,MVAINJ,4,06/22/2020 03:58:07 PM,Y,23,06/22/2020 03:58:19 PM,...,62.0,47.0,311.0,21.0,11.0,N,N,N,N,chunk172.csv
13116,200865674,2020-03-26 19:33:19,DIFFFC,2,DIFFFC,2,03/26/2020 07:33:50 PM,Y,31,03/26/2020 07:34:08 PM,...,103.0,27.0,412.0,29.0,5.0,N,N,N,N,chunk168.csv

In [28]:
## Programmatically capture the 2245th FINAL_CALL_TYPE value and store in a variable.
final_call_type = ems2020_excerpt_df["FINAL_CALL_TYPE"].iat[2244]
final_call_type

'STAB'

## Targeting an Excel sheet

Use the Customs and Border Protection data in this ```multi-data.xlsx``` workbook to answer the following questions.

Create a dataframe called ```cbp_df```.

In [30]:
## import data here
cbp_df = pd.read_excel("data-raw/multi-data.xlsx", sheet_name = "CBP", skiprows= 6)

In [31]:
## call the top 15 rows

cbp_df.head(15)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
0,2017-01-20 00:10:00,2017-01-20 10:08:00,9.950000,6-8 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN
1,2017-01-20 00:15:00,2017-01-24 17:30:00,113.233333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
2,2017-01-20 00:22:00,2017-01-24 17:47:00,113.416667,3-5 years,Female,BRAZIL,SBO,(b)(7)(E ),NaN
3,2017-01-20 00:30:00,2017-01-21 06:35:00,30.083333,12-14 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
4,2017-01-20 00:30:00,2017-01-21 13:03:00,36.533333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
5,2017-01-20 00:30:00,2017-01-21 15:30:00,38.983333,Under 1 year,Male,HONDURAS,SBO,(b)(7)(E ),NaN
6,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
7,2017-01-20 00:35:00,2017-01-20 15:14:00,14.633333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
8,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,3-5 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
9,2017-01-20 00:35:00,2017-01-21 11:52:00,35.266667,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
10,2017-01-20 00:45:00,2017-01-20 13:15:00,12.500000,15-18 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
11,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
12,2017-01-20 01:19:00,2017-01-21 02:30:00,25.166667,15-18 years,Male,INDIA,SBO,(b)(7)(E ),NaN
13,2017-01-20 01:20:00,2017-01-24 17:30:00,112.166667,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
14,2017-01-20 01:20:00,2017-01-20 13:40:00,12.333333,9-11 years,Female,EL SALVADOR,SBO,(b)(7)(E ),NaN

In [34]:
## get basic overview of the data
## what datatypes do the different columns hold?
## how many rows and columns are there
cbp_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95721 entries, 0 to 95720
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   date_in           95721 non-null  datetime64[ns]
 1   date_out          95223 non-null  datetime64[ns]
 2   hours_in_custody  95506 non-null  float64
 3   age_group         95716 non-null  object
 4   gender            95721 non-null  object
 5   citizenship       95721 non-null  object
 6   border            95721 non-null  object
 7   sector            95721 non-null  object
 8   field_office      0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(5)
memory usage: 6.6+ MB

In [36]:
## call the bottom 3
cbp_df.tail(3)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
95718,2018-06-02 13:05:00,2018-06-05 23:35:00,82.483333,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
95719,2018-06-02 13:05:00,2018-06-04 00:54:00,35.800000,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
95720,2018-06-02 13:20:00,2018-06-06 07:27:00,90.100000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN

In [38]:
## call a sample of 20
cbp_df.sample(20)

,date_in,date_out,hours_in_custody,age_group,gender,citizenship,border,sector,field_office
26685,2017-09-05 09:55:00,2017-09-06 08:14:00,22.300000,6-8 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
46476,2017-12-08 10:12:00,2017-12-10 10:57:00,48.733333,3-5 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
70436,2018-03-20 00:30:00,2018-03-21 18:06:00,41.583333,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
42477,2017-11-23 20:00:00,2017-11-27 14:48:00,90.783333,1-2 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
63739,2018-02-21 21:39:00,2018-02-23 15:27:00,41.783333,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
19923,2017-07-28 15:40:00,2017-07-30 16:04:00,48.383333,12-14 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
44855,2017-12-01 19:08:00,2017-12-04 09:50:00,62.683333,9-11 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
38785,2017-11-09 15:00:00,2017-11-12 10:54:00,67.883333,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
67448,2018-03-09 19:05:00,2018-03-11 00:51:00,29.750000,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
21300,2017-08-06 16:00:00,2017-08-08 14:54:00,46.883333,6-8 years,Male,EL SALVADOR,SBO,(b)(7)(E ),NaN
52707,2017-12-29 20:00:00,2017-12-30 16:47:00,20.766667,9-11 years,Female,MEXICO,SBO,(b)(7)(E ),NaN
54010,2018-01-10 09:15:00,2018-01-12 11:13:00,49.950000,3-5 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
59503,2018-02-01 22:45:00,2018-02-02 14:49:00,16.050000,9-11 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
90326,2018-05-19 20:20:00,2018-05-21 16:06:00,43.750000,6-8 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
55205,2018-01-14 22:17:00,2018-01-16 08:58:00,34.683333,15-18 years,Male,GUATEMALA,SBO,(b)(7)(E ),NaN
45748,2017-12-05 12:50:00,2017-12-06 16:15:00,27.400000,6-8 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN
15078,2017-06-23 00:45:00,2017-06-25 05:49:00,53.066667,15-18 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
60550,2018-02-06 13:51:00,2018-02-06 17:06:00,3.250000,1-2 years,Male,MEXICO,SBO,(b)(7)(E ),NaN
19403,2017-07-24 21:30:00,2017-07-27 11:38:00,62.116667,12-14 years,Female,GUATEMALA,SBO,(b)(7)(E ),NaN
62773,2018-02-17 19:45:00,2018-02-19 14:51:00,43.083333,15-18 years,Male,HONDURAS,SBO,(b)(7)(E ),NaN

In [42]:
## Programmatically capture the 8th hours_in_custody value and store in a variable.
hours_held = cbp_df["hours_in_custody"].iat[7]
hours_held

14.6333333333333